# Generated by Django 2.2.6 on 2020-09-10 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200910_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='ro_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.room_offer'),
        ),
    ]
