# Generated by Django 2.2.6 on 2020-10-11 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200910_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='cID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.customer'),
        ),
    ]
