# Generated by Django 2.1.7 on 2020-10-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201011_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='confirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_date', models.DateField()),
                ('con_time', models.TimeField()),
                ('con_details', models.CharField(max_length=200)),
                ('con_trans_id', models.CharField(max_length=30)),
                ('con_amount', models.FloatField()),
                ('con_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='outstanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_date', models.DateField()),
                ('out_time', models.TimeField()),
                ('out_details', models.CharField(max_length=200)),
                ('out_trans_id', models.CharField(max_length=30)),
                ('out_amount', models.FloatField()),
                ('out_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('details', models.CharField(max_length=200)),
                ('trans_id', models.CharField(max_length=30)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
